spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_management
    username: root
    password: aakash
  jpa:
    show-sql: true
    generate-ddl: false    
